function window = hammingWindow(gamma,omega)
    window = 1./(2*pi)./2.*d_gamma(gamma,omega) + ...
    1./(2*pi)./4*d_gamma(gamma,omega-pi/gamma) + ...
    1./(2*pi)./4*d_gamma(gamma,omega+pi/gamma);
end